.gitignore, .travis.yml, README.md, index.js, package.json, test.js
=> Initial release

package.json, test.js
=> Increase test coverage

index.js, package.json, test.js
As titled.
Also added support for streams 1, see https://github.com/fastify/fastify/pull/648.
=> Updated to support the latest version of fastify

index.js, test.js
solves https://github.com/fastify/fastify-compress/issues/24
=> Dont support br header if brotli option not set

index.js, package.json, test.js
Ref https://github.com/fastify/fastify-static/issues/52.
=> Remove content-length when compressing

index.js
=> Log debug instead of warn for missing payload

package.json
=> fix(package): update unzipper to version 0.9.11

package.json
=> Pin into-stream to v4

README.md, index.js, test.js
=> feat: support native Brotli

index.d.ts, package.json, test/test.js, test/types/index.ts, test/types/tsconfig.json
Hi
It's a great plugin. 
And we should make it accessible for TypeScript developers.
It's related to https://github.com/fastify/fastify-compress/issues/54
=> Add types definition for TS integration

package.json
=> fix(package): update unzipper to version 0.10.1

package.json
=> chore(package): update @types/node to version 12.0.8

package.json
=> chore(package): update @types/node to version 12.12.12

package.json
=> Lock iltorb depepdency

index.js
Drop the log line when there is no data to compress.
https://github.com/fastify/fastify-compress/issues/114
=> Don't log if there is no data to compress

index.d.ts, package.json
=> Fix types for v3

index.d.ts, package.json
=> Update typescript defs

index.js
=> nitpick - use 'include' instead of 'some'

README.md
- [ x] documentation is changed or added
- [x ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
=> chore: fix heading in readme

.taprc, package.json
also fixes a broken script and removes redundant ones
Ref: https://github.com/fastify/fastify-sensible/pull/138#discussion_r1276157318
Removed check-coverage from tap config since it's [on by default](https://node-tap.org/docs/coverage/#maximal-coverage-)
=> remove linting from the test script

index.js, test/global-compress.test.js, test/global-decompress.test.js, test/routes-compress.test.js, test/routes-decompress.test.js, test/utils.test.js
Same as https://github.com/fastify/fastify-static/pull/407
=> perf: use node: prefix for builtins

package.json, test/regression/issue-288.test.js
=> refactor: remove `node-fetch` dev dependency 

.github/workflows/ci.yml, .taprc, package.json
=> Merge `next` into `master`

index.js, package.json
=> chore: update fastify version to `5.x`

index.js
=> refactor(index): remove unused catch bindings

README.md
See https://github.com/fastify/fastify-accepts/pull/180
=> docs(readme): point ci badge at master/main branch

package.json
=> chore(package): add funding and contribs

index.js, test/global-compress.test.js, test/global-decompress.test.js, test/regression/issue-288.test.js, test/routes-compress.test.js, test/routes-decompress.test.js, types/index.test-d.ts
=> refactor: prefix unused params with underscores

README.md
=> docs(readme): conciseness improvements

README.md
This is a batch PR, so may have some issues. Please review changes.
=> docs(readme): update plugin version syntax

.github/workflows/ci.yml, README.md
This is a batch PR. This change stops security tools like step-security from complaining.
=> ci: set permissions at workflow level
