fastify/fastify-compress

README.md
index.js
test.js

According to [https://tools.ietf.org/html/rfc7231#section-5.3.4](https://tools.ietf.org/html/rfc7231#section-5.3.4) a missing accept-encoding header is valid.
In this case no error should be send and the payload should not be compressed.

Allow missing accept-encoding header

---

README.md
index.js
test.js

This PR adds support for an asterisk `*` in the `accept-encoding` header.

Support asterisk in accept-encoding header

---

index.js
package.json
test.js

- Updates to fastify@0.39.1
- Updates to tap@11.0.1
- Adds `name` property to plugin-meta. see: https://github.com/fastify/fastify-plugin/issues/17#issuecomment-355972265
Please note, that in order to make test pass, I had to change `compress` to `send` at
https://github.com/lependu/fastify-compress/blame/71b4f7f8754589c78f94e7277de3342d001d733b/test.js#L371 
Otherwise it compresses the content twice. I could not figure out why is that, so I guess it needs a deeper review.

Updates fastify, plugin-meta

---

index.js
test.js

This will allow whitepsaces in accept-encoding headers.
While working on https://github.com/fastify/fastify-compress/pull/25 I discovered that accept headers with whitespace did not work.
Taken from a real request in the wild ```accept-encoding: "br, gzip, deflate"```

accept-encoding can contain whitespace

---

README.md
index.js
test.js

The itch I'm scratching is I couldn't compress a protobuf content type, as it wasn't in mime-db or in the `compressibleTypes` constant. I was going to add it to `compressibleTypes`, but that didn't seem like a sustainable solution, so I made the `compressibleTypes` regex user configurable.
Since the types that were in `compressibleTypes` are also in mime-db, I'm guessing this is used to short circuit the mime-db check for performance. Figured overwriting `compressibleTypes` this way would be more performant than adding an additional regex check for a user passed expression (i.e. compressibleTypes.test(type) || someuserstuff.test(type)).

make compressibleTypes user settable so custom types can be compressed

---

README.md
index.js
package.json
test.js

This PR adds support for providing custom implementations of `createGzip` and `createDeflate` and inflating already-compressed response bodies if the client doesn't support compression.
Overriding `createGzip` allows swapping out gzip with [`pigz`](https://github.com/madler/pigz), useful for multi-megabyte dynamic payloads:
```js
const es = require('event-stream')
const { spawn } = require('child_process')
const pigz = { createGzip: () => es.child(spawn(`pigz`, ['-c'])) }
fastify.register(compressPlugin, { global: false, zlib: pigz })
```
Inflating compressed content is a convenience feature for services interfacing with clients like `curl`, or embedded devices, especially in a mesh scenario where data is produced and consumed deflated until it hits the edge. That said, I recognize it …

support custom deflate, inflate compressed bodies

---

README.md

fastify.register(require('fastify-compress'), { global: false })
^
TypeError: fastify.register is not a function

This closes issue #58

---

index.js
package.json
test/test.js

This adds support for quality values in the `accept-encoding` header.
Closes #70

Add support for quality values

---

package.json

There is no reasons to lock this dep.
Introduced here: https://github.com/fastify/fastify-compress/commit/3249c8ea1639cc37d5c077c9f0287f901de02408
Closes #81

Greenkeeper/minipass 2.9.0

---

README.md
index.js
test/test.js

Fixes #85 
- [Ran test, benchmark is not a script] run `npm run test` and `npm run benchmark`
- [Tests succeeded] tests and/or benchmarks are included
- [Yes] documentation is changed or added
- [YES] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

Remove HTTP406 errors, allow variable case in accept encoding header to align with RFC 7231

---

README.md
index.d.ts
index.js
package.json
test/test.js
test/types/index.ts

While implementing the option to choose the order of accepted encodings, it was less code and more elegant to also let consumers avoid certain encodings entirely. This would be useful in the case of misbehaving downstream boxes.
Also changes default priority to prefer Brotli to gzip.
Fixes #61, fixes #43, closes #62.

Allow customizing used encodings

---

README.md
index.d.ts
index.js
package.json
test/test.js

created new function in the options to allow users to specify a custom response when the encoding is unsupported.
I could not follow the original design of using the reply.send() function in the callback because you can't call that function in the onSend hook.

Allowing custom error messaging on unsupported encoding

---

index.js
test/test-global.js

https://github.com/jshttp/mime-db package has many content type for which the value of `compressible` is undefined. When this is encountered, this package was wrongly compressing those mime types. One such example is `image/webp` type.
This PR fixes that wrong behavior and also adds test to prevent it from happening again in future.

bug fix - undefined value of compressible now does not compress

---

README.md
index.d.ts
index.js
package.json
test/index.test-d.ts
test/test-global-compress.js

https://github.com/fastify/fastify-compress/issues/106
This does not include tests or a benchmark - just wanted to quickly throw together a first-step in the direction of completing this issue: https://github.com/fastify/fastify-compress/issues/106
This also does not include documentation, simple example is as follows:
```
server.register(fastifyCompress, {
brotliOptions: {
params: {
[zlib.constants.BROTLI_PARAM_MODE]: zlib.constants.BROTLI_MODE_TEXT, // useful for APIs that primarily return text
[zlib.constants.BROTLI_PARAM_QUALITY]: 4, // default is 11, max is 11, min is 0
},
},
zlibOptions: {
level: 9, // default is 9, max is 9, min is 0
}
});
```

Support passing zlibOptions and brotliOptions

---

index.js
test/test-global-compress.js

This PR fixes following crash bug in onEnd handler:
```
webpack-internal:///../../node_modules/fastify-compress/index.js:396
this.raw.log.error(err);
^
TypeError: Cannot read property 'error' of undefined
at _Reply.onEnd (webpack-internal:///../../node_modules/fastify-compress/index.js:396:18)
at eval (webpack-internal:///../../node_modules/pump/index.js:75:7)
at f (webpack-internal:///../../node_modules/once/once.js:25:25)
at Duplexify.eval (webpack-internal:///../../node_modules/pump/index.js:31:21)
at Duplexify.f (webpack-internal:///../../node_modules/once/once.js:25:25)
at onclosenexttick (webpack-internal:///../../node_modules/end-of-stream/index.js:54:73)
at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
related:
- Removed modifyCoreObjects option, …

fix logger reference in onEnd

---

index.js

Just re-doing what had already been done: https://github.com/fastify/fastify-compress/pull/115
https://github.com/fastify/fastify-compress/issues/114 https://github.com/fastify/fastify-compress/issues/127

Do not log missing payload

---

index.js
test/test-global-compress.js

Server-sent events (SSE) are designed to be realtime; by enabling the compression plugin on this content type the latency between writing data to the stream and receiving it on the client can be indefinitely long. This PR prevents compression on event streams, leading to SSE behaving as expected.
This change was provided via the GitHub interface, so I'm hoping that the tests/benchmarks are ran by your CI.
```
> /^text\/|\+json$|\+text$|\+xml$|octet-stream$/.test('text/event-stream')
true
> /^text\/(?!event-stream)|\+json$|\+text$|\+xml$|octet-stream$/.test('text/event-stream')
false
> /^text\/(?!event-stream)|\+json$|\+text$|\+xml$|octet-stream$/.test('text/plain')
true
```

fix: prevent compressing text/event-stream

---

index.js
test/test-global-compress.js

[bug] While replying with brotly encoding, vary header was missing
Since the response body differs based on the Accept-Encoding from the request header, we need to add Vary Header of "accept-encoding" to **all** responses processed with the fastify-compress library so that CDNs and other caches work properly.

Added Vary header to all responses

---

.github/workflows/ci.yml

The wrong name was causing Node 14 to be used in all builds.

ci: fix node-version matrix parameter name

---

index.js
test/test-global-compress.js

fix: avoid adding "accept-encoding" to vary header if already set

---

index.js
test/global-compress.test.js

fix: content encoding priorities

---

README.md
index.js
test/global-compress.test.js
types/index.d.ts
types/index.test-d.ts

Support Functions for customType option

---

index.js
test/global-compress.test.js

Hey there, quick fix to fix support for [content-type syntax](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#syntax).
I encountered this issue after using an endpoint that was specifying encoding and compression wasn't being applied.

Fix default supported content types

---

index.js

See https://github.com/fastify/fastify-helmet/issues/236

refactor(index): replace `typeof` undefined check

---

README.md
index.js

BREAKING CHANGE: The default brotli quality value currently is 11, which is not meant to be used in an on the fly compression context. Change this to a more reasonable default value of 4.

perf!: reduce default brotli compression factor to 4, was before 11 (maximum)

---

index.js
test/global-compress.test.js
types/index.test-d.ts

I encounted a remarkable performance slow down after migrating from Koa. 
Although the doc mentions [fastify/compress](https://github.com/fastify/fastify-compress/blob/master/README.md?plain=1#L172) already sets the compression level to 4, but it takes too long to compress (3MB for 5 sec) a json. I guess it is configured unexpectedly by default. 
After some investigation, it could be related to the previous merge request #278. 
Unless I explicitly set the compression level to `4`, I will get `11` (BROTLI_DEFAULT_QUALITY). 
The compression level is a member of `brotliOptions.params` not `brotliOptions`. https://nodejs.org/api/zlib.html#class-brotlioptions
And unfortunately the global default option is overwritten by custom option afterwards …

fix: default brotliOptions does not applied to createBrotliCompress and createBrotliDecompress

---

package.json
test/issue-288.test.js
test/regression/issue-288.test.js

Polish test case for PR: replace `into-stream` to `Readable.from`

---

.c8rc
.taprc
index.js
package.json
test/global-compress.test.js
test/global-decompress.test.js
test/regression/issue-288.test.js
test/routes-compress.test.js
test/routes-decompress.test.js
test/utils.test.js

use node:test instead of tap

---

README.md
package.json
types/index.d.ts
types/index.test-d.ts

See https://github.com/fastify/fastify/pull/5896. This is a batch PR, so may have some issues. Please review changes.

types: use `node:` prefix for builtins

---

README.md

Previous icon was not visible in Safari. See https://github.com/fastify/fastify/pull/6132#discussion_r2097602170

docs: use cross-platform compatible info emoji
